import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const link = [
  {
    label: 'Home',
    route: '/'
  },
  {
    label: 'About',
    route: '/about'
  }
]

export default function RootLayout ({ children }) {
  return (
    <html lang='es'>
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              {
                link.map(item => (
                  <li key={item.label}>
                    <Link href={item.route}>{item.label}</Link>
                  </li>
                ))
              }
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
